### ISSUE TITLE
Add TODO list 

### ISSUE THREAD

**Issue by Ishan-Saini** [Raghwendra-Dey/productivity_meter#14]
Right now, this app is focused on counting the number of problems a user solves in a time duration. But to widen the scope of this project we need something through which a user can also keep track of their other tasks.
So the idea is to have a To-do list which will help users track their pending tasks throughout the day. 

Features of this Todo list - 

1.  **Completion** - A user should be able to cross out a task (It will still be shown in UI with a strikethrough line).
2. **Deletion** - A user should be able to remove a task from the UI itself.
3. **Updation** - A user should be able to update a task at any point of time.
4. (OPTIONAL) Problem counter could be synchronized with No. of task completed. For ex. If a user completes his/her task then there should be an automatic increment in No. of problems solved.

Note : It'd be better if the to-do list is in a 100 viewport height itself.

**Comment by Bbiswabasu** [comment]
This seems interesting and I would like to work on this

**Comment by TusharDasMe** [comment]
Can I work on this ?

**Comment by siddhant094** [comment]
it would be great if you could assign this to me

**Comment by Raghwendra-Dey** [comment]
Hello @Ishan-Saini @Bbiswabasu @siddhant094 @TusharDasMe . I am glad to see that all of you are interested to contribute towards this feature. This is a very good opportunity for all of you to collaborate, and learn team work values. All of you would be working on this feature. I would assign one of you to put up the boilerplate code, and then we would assign specific feature of the TODO list to each one of you.
First we should decide upon the basic layout and the features of the TODO list.
I suggest this type of layout, which is very similar to the `google keep` layout.
![IMG_20201206_215039](https://user-images.githubusercontent.com/45457947/101286004-3c761000-380e-11eb-9ea8-2b20c812f752.jpg)
Features I propose:
1. `ADD` button which increases the number of current rows by one.
2. The height of the list should be fixed with scrollbar showing up whenever the height becomes insufficient to accomodate the given entries.
3. Each entry should be a text field, so that we can directly edit that entry by clicking on it. Just like in google keep.
4. Checkbox to show the done/undone status of the entry. If the entry is done, then it would be stricked off.
5. For the time being the stricked entry would be in the same place, as it was before. No need to shift it towards the bottom of the list, like google keep does, We may introduce this feature as a later addon.

**Comment by Raghwendra-Dey** [comment]
@Ishan-Saini I think the `4th point` suggested by you would be unusual, since number of problems solved is never a TODO. A TODO entry is just `Practice problem solving` / `resolve the assigned issue#4` . And then its upon the user how many problems he wants to solve. So, I think we should keep the problem counter as it is for the time being.

**Comment by Ishan-Saini** [comment]
@Raghwendra-Dey  Alright, lets discard the 4th point.
The basic design of the list LGTM tho.

**Comment by Bbiswabasu** [comment]
@Raghwendra-Dey I will be doing the task of adding elements to Todo List and @Ishan-Saini will be writing event listeners for each element. So, I think for my part, there is no need to add separate issue.
