### ISSUE TITLE
Add a navbar in the header

### ISSUE THREAD

**Issue by Nishant2907** [Raghwendra-Dey/productivity_meter#16]
For setting a basic layout, we will have to start from adding the top most thing a website requires for sure- A Navbar.

**Comment by Nishant2907** [comment]
@Raghwendra-Dey I would like to work on adding the header to the website. What I will do is that I will make a cover image on the top of the screen, covering 60 - 70% of the screen with a image and a navbar in it.

**Comment by Raghwendra-Dey** [comment]
Could you draw the look of the page with the header and footer you are thinking of adding, then the picture would be more clear.
One small suggestion, Don't make the header cover more area than 10-20% of the initial height of the screen, since our main product are the timers, and all. So, We don't want to trouble the user with scrolling to find them everytime.
Please make the size adjustments accordingly, and post a picture of the same, maybe drawn in a copy.
