### ISSUE TITLE
Displaying average time spent per problem in the previous session whenever clear/reset button is pressed

### ISSUE THREAD

**Issue by sourav-suku** [Raghwendra-Dey/productivity_meter#20]
As the project is aimed at increasing productivity in problem solving, approximate idea of time spent per problem will help in increasing the speed of problem solving.
So the idea is to display the average time spent per problem whenever clear or reset button is pressed, as a message.
When no problem is solved in the previous session then accordingly message can be provided.

**Comment by Raghwendra-Dey** [comment]
@sourav-suku actually that would cause a lot of burden on the user to repeatedly press buttons, also, this project mainly focuses on measuring the small small time wastage, due to small distractions like, calling a friend, checking social media for checking notifications.
But your idea could also be implemented without troubling the user with extra button pressing things. Maybe we can add a small space for showing the average time of the user, and update that, whenever a button named `Go` is pressed, we would start the timing counter, and whenever the `+1` button is pressed, that means he is done with the previous problem, so we can take that time and add that to the running average. Let's say the user wants to do some other work (maybe reviewing a recent PR :p)  so he can just stop the `Go` button, that would stop the average timer counter. 
Here what the problem counter block would look like after implementing this idea:

![IMG_20201207_154336](https://user-images.githubusercontent.com/45457947/101338634-426a0080-38a3-11eb-91fd-90a05533c5e5.jpg)

Features:
*  If `Go` Button is not pressed, the average timer should be showing 0.
* If the `Go` Button is pressed then only, the average time thing should work, and record the timings.
* When `+1` button is pressed, it records the current timestamp, as the starting timestamp, then, when next time `+1` is again pressed, it signifies, that the user is done with one problem, so, it should add the time interval i.e. `current_timestamp - prev_timestamp` to the average and update the average.

Problems:
* what to do, when `-1` is pressed repeatedly? since we can't save indivisual timestamps for all the previous problems, to subtract it when `-1` is pressed.
=> I suggest maybe, we can keep the average as it is, and do nothing when `-1` is pressed. Maybe we can, get rid of this problem on later stages.
If you have any solution then please comment.

**Comment by Raghwendra-Dey** [comment]
@sourav-suku would you like to do this?

**Comment by Raghwendra-Dey** [comment]
Please give some other name to the new introduced button, since `Go` name is already in use by the `timers`.
Name it `Record` instead.

**Comment by sourav-suku** [comment]
> @sourav-suku would you like to do this?

Thank you for your response
Yes,I would like to do this

**Comment by sourav-suku** [comment]
> Please give some other name to the new introduced button, since `Go` name is already in use by the `timers`.
> Name it `Record` instead.

Ya.I would do that

**Comment by sourav-suku** [comment]
@Raghwendra-Dey
From what you said above I realise that u are planning to calculate the average "actual" time given by the user per problem.
But instead of this we can calculate average "total" time ("actual time" + "time wasted") which essentially will serve the same purpose as the former.The latter can also be implemented easily and even reduces the burden from users side as no extra buttons have to be clicked.

**Comment by sourav-suku** [comment]
The main purpose of including the average time per problem is that the user get a first hand impression about their time utilization so that they can plan to solve the next problem quickly

**Comment by sourav-suku** [comment]
Regarding Implementation
We can take total time devoted and problem count for calculating the average total time (Total time devoted/(Problems Count)  
When count is zero average is also kept zero,.
The average is updated whenever +1 is pressed and reset to zero when reset button is pressed.

**Comment by sourav-suku** [comment]
#36

**Comment by sourav-suku** [comment]
I have created a pull request implementing the above said idea
