### ISSUE TITLE
Proper alignment and display of an additional button

### ISSUE THREAD

**Issue by anjali-2504** [Raghwendra-Dey/productivity_meter#30]
Basically for the count of the problems i added an extra button in place where reset currently is. And  placing the reset button down the black area just like we have the Go  button below the timer box. Apart  from this I also thought of adding a sound effect on clicking the button Go and after clicking Stop  just the way stopwatches have. And similarly , there can be a heading at the top(with an iconic name) and an image beside sort of an icon may be.
And yes a link at last with the manual page linked to it so that someone new can read the rules to operate it by clicking it. 
Other issues which came to my mind are like  having a data box showing the number of users who are using it per day and an option fir the users to rate the work. 
I  am very curious to contribute to this project if  you assign me these issues.

**Comment by Raghwendra-Dey** [comment]
> Basically for the count of the problems i added an extra button in place where reset currently is. And placing the reset button down the black area just like we have the Go button below the timer box.

I could not follow you on this. Could you put a diagram dipicting what exactly are you talking about.

> Apart from this I also thought of adding a sound effect on clicking the button Go and after clicking Stop just the way stopwatches have.

These sound effects may unnecessarily distract the user while studying. We would be looking at making a spotify addon with this product on later stages, where the user could be able to play music of his choice.

> And similarly , there can be a heading at the top(with an iconic name) and an image beside sort of an icon may be.

Please provide some diagrams.

> And yes a link at last with the manual page linked to it so that someone new can read the rules to operate it by clicking it.

I think we can add all these things in the footer, which is already in making. We can put the link to the `Readme`, since it already have all the things required for the manual.

> Other issues which came to my mind are like having a data box showing the number of users who are using it per day and an option fir the users to rate the work.

This sounds interesting, could you elaborate on how exactly do you intend to achieve it. If yes, then, please go ahead and open an issue regarding it, and work on it. If no, then I suggest you first figure out ways to achieve this. We can always pick this up on later stages.
