### ISSUE TITLE
Adding hovering style to buttons

### ISSUE THREAD

**Issue by aalokagrawal** [Raghwendra-Dey/productivity_meter#31]
Make buttons more stylish and while clicking them it should look like we are pressing a real button.They should come up while hover and should go inside when pressed giving a feel like it is actually getting pressed.

**Comment by Raghwendra-Dey** [comment]
@aalokagrawal sorry hovering things is already in progress. I suggest you get in touch with @Nishant2907 since he is currently working on three issues simultaneously (#16 , #17 , #23 ). He would require your help to deliver them quickly.
Also @aalokagrawal please join [this](https://gitter.im/productivity_meter/UI_works) channel.
